### ISSUE TITLE
packrat package submissions fail due to failures in jetpack

### ISSUE THREAD

**Issue by kevinushey** [ankane/jetpack#22]
E.g.

```
    ── Error (test-jetpack.R:37:3): it works ───────────────────────────────────────
    Error: Errors occurred when fetching source files:
    Error in getSourceForPkgRecord(pkgRecord, sourceDir, availablePkgs, repos) :
      Failed to retrieve package sources for packrat 0.6.0 from CRAN (internet connectivity issue?) [0.5.0 is current]
```

Would it be possible for `jetpack` to handle the case where the version of Packrat being checked is newer than what is declared to be available on CRAN?

**Comment by ankane** [comment]
Hey @kevinushey, sorry that's holding things up. I think it's due to the `packrat::init()` call, which tries to download Packrat from CRAN. Is there a way for that method to use a local copy of Packrat instead?

Feel free to move forward with the submission process if possible, as the tests should work again once the new version is out. Since Packrat is soft deprecated, I've also been planning to move Jetpack to renv. It's mostly done, so will try to get that out.
